title: Liu Huanyu
url: "https://liuhuanyu.cn"
# baseurl: "/liuhyCV.github.io"
baseurl: ""

markdown: kramdown
#ins_logo: "./bits-logo.png"
remote_theme: ankitsultana/researcher@gem

tracking_id: UA-144113550-1

#footer: yes
#footer_url: "https://github.com/ankitsultana"
#footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

# nav:
#  - name: "About_English"
#    link: "about_english"
#  - name: "Blog"
#    link: "blog"
#  - name: "Contact"
#    link: "contact"
